spring:
  cloud:
    contract:
      verifier:
        enabled: false
  application:
    title: "Axon :: Sample Project :: Query"
    name: "query-medisafe"


  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# used for trackingtokens
axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson
  amqp:
    exchange: myExchange

server:
  port: 8000

---
spring:
  config:
    activate:
      on-profile: prod
