spring:
  cloud:
    contract:
      verifier:
        enabled: false
  application:
    title: "Axon :: Sample Project ::"
    name: "medisafe"

# used for trackingtokens
axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson
---
spring:
  config:
    activate:
      on-profile: prod
