spring:
  cloud:
    contract:
      verifier:
        enabled: false
  application:
    title: "Axon :: Sample Project :: Command"
    name: "command-medisafe"


  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8080

# used for trackingtokens
axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson

  amqp:
    exchange: SafeCreatedEvent
#  eventhandling:
#    processors:
#      amqpEvents:
#        source: amqpMessageSource
#        mode: subscribing
#
#      handlerServicebus:
#        source: amqpMessageSource
#        mode: subscribing


axoniq:
  console:
    credentials: "940a3681-0:8670bbe863b24e5aa5745b7a0bd7aacd"

---
spring:
  config:
    activate:
      on-profile: prod
